---
title: "Untitled"
author: "Emma Jones"
date: "4/13/2022"
output: html_document
params:
  StationID:
    label: 'StationID'
    value: '2-JKS018.68'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(geojsonsf)

```


blank

```{r}
 suppressWarnings(geojson_sf(
          paste0("http://apps.deq.virginia.gov/arcgis/rest/services/public/WQM_STATIONS_ALL/MapServer/0/query?&where=STATION_ID%3D%272-JKS023.61%27&outFields=*&f=geojson")))[1,] %>%
            #"http://gis.deq.virginia.gov/arcgis/rest/services/staff/DEQInternalDataViewer/MapServer/104/query?&where=STATION_ID%3D%272-JKS023.61%27&outFields=*&f=geojson")))[1,] %>%
        mutate(WQM_YRS_YEAR = ifelse(!is.na(WQM_YRS_YEAR), lubridate::year(as.Date(as.POSIXct(WQM_YRS_YEAR/1000, origin="1970-01-01"))), NA)) %>%
        st_drop_geometry()
```


pull from REST public
```{r}
suppressWarnings(
      geojson_sf(
        paste0("http://apps.deq.virginia.gov/arcgis/rest/services/public/WQM_STATIONS_ALL/MapServer/0/query?&where=STATION_ID%3D%27",
          #"http://gis.deq.virginia.gov/arcgis/rest/services/staff/DEQInternalDataViewer/MapServer/104/query?&where=STATION_ID%3D%27",
               toupper(params$StationID),"%27&outFields=*&f=geojson")))
```

pull from REST public https

```{r}
suppressWarnings(
      geojson_sf(
        paste0("https://apps.deq.virginia.gov/arcgis/rest/services/public/WQM_STATIONS_ALL/MapServer/0/query?&where=STATION_ID%3D%27",
          #"http://gis.deq.virginia.gov/arcgis/rest/services/staff/DEQInternalDataViewer/MapServer/104/query?&where=STATION_ID%3D%27",
               toupper(params$StationID),"%27&outFields=*&f=geojson")))
```

pull from REST staff

```{r}
suppressWarnings(
      geojson_sf(
        paste0("http://gis.deq.virginia.gov/arcgis/rest/services/staff/DEQInternalDataViewer/MapServer/104/query?&where=STATION_ID%3D%27",
          #"http://gis.deq.virginia.gov/arcgis/rest/services/staff/DEQInternalDataViewer/MapServer/104/query?&where=STATION_ID%3D%27",
               toupper(params$StationID),"%27&outFields=*&f=geojson")))
```


pull from REST staff https
```{r}
# suppressWarnings(
#       geojson_sf(
#         paste0("https://gis.deq.virginia.gov/arcgis/rest/services/staff/DEQInternalDataViewer/MapServer/104/query?&where=STATION_ID%3D%27",
#           #"http://gis.deq.virginia.gov/arcgis/rest/services/staff/DEQInternalDataViewer/MapServer/104/query?&where=STATION_ID%3D%27",
#                toupper(params$StationID),"%27&outFields=*&f=geojson")))
```
